# Generated by Django 5.1.7 on 2025-03-22 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10, unique=True)),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bus')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='bookings.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='bookings.station')),
            ],
        ),
        migrations.CreateModel(
            name='BusStationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bus')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.station')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='ending_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_buses', to='bookings.station'),
        ),
        migrations.AddField(
            model_name='bus',
            name='starting_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_buses', to='bookings.station'),
        ),
        migrations.AddField(
            model_name='bus',
            name='stations',
            field=models.ManyToManyField(related_name='passing_buses', through='bookings.BusStationTime', to='bookings.station'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('payment_status', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bus')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_bookings', to='bookings.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_bookings', to='bookings.station')),
            ],
        ),
    ]
